In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('mp.csv')
df

formula    x1  x2    x3    x4  x5     x6   x7    x8    x9  x10   x11   x12  \
0     CaAg  1.00   2  1.22  1.84  20   6.11  154  1757  1.93   11  0.47  1.58   
1     BaPb  0.89   2  1.52  2.29  56   5.21  142  2171  2.33    4  0.71  1.06   
2     BaGe  2.01   4  0.64  0.90  32   7.90  331  3103  0.89    2  1.52  2.29   
3     CaGe  1.00   2  1.22  1.84  20   6.11  154  1757  2.01    4  0.64  0.90   
4     CaSi  1.90   4  0.66  0.88  14   8.15  384  2628  1.00    2  1.22  1.84   
5     CaSn  1.00   2  1.22  1.84  20   6.11  154  1757  1.96    4  0.78  1.06   
6     SrSi  1.90   4  0.66  0.88  14   8.15  384  2628  0.95    2  1.36  2.05   
7     SrGe  2.01   4  0.64  0.90  32   7.90  331  3103  0.95    2  1.36  2.05   
8      TlI  2.66   7  0.71  0.87  53  10.45   21   459  1.62    3  0.67  1.13   
9     CdAg  1.93  11  0.47  1.58  47   7.58  251  2436  1.69   12  0.67  1.26   
10    LiAg  0.98   1  0.99  1.93   3   5.39  146  1615  1.93   11  0.47  1.58   
11    MgAg  1.31   2  0.86  1.42  12   7.65  127  1363  1.93   11  0.47  1.58   
12    ZnAg  1.65  12  0.62  1.17  30   9.39  119  1180  1.93   11  0.47  1.58   
13    CdAu  1.69  12  0.67  1.26  48   8.99  100  1038  2.54   11  0.22  1.32   
14    LiAu  0.98   1  0.99  1.93   3   5.39  146  1615  2.54   11  0.22  1.32   
15    MgAu  1.31   2  0.86  1.42  12   7.65  127  1363  2.54   11  0.22  1.32   
16    RbAu  0.82   1  1.44  2.86  37   4.18   72   961  2.54   11  0.22  1.32   
17    ZnAu  1.65  12  0.62  1.17  30   9.39  119  1180  2.54   11  0.22  1.32   
18    BeCu  1.57   2  0.66  0.96   4   9.32  292  3243  1.90   11  0.37  1.48   
19    CaCd  1.00   2  1.22  1.84  20   6.11  154  1757  1.69   12  0.67  1.26   
20    CaTl  1.00   2  1.22  1.84  20   6.11  154  1757  1.62    3  0.67  1.13   
21    CaHg  1.00   2  1.22  1.84  20   6.11  154  1757  2.00   12  0.57  1.21   
22    SrCd  0.95   2  1.36  2.05  38   5.70  144  1657  1.69   12  0.67  1.26   
23    ZnCu  1.90  11  0.37  1.48  29   7.73  300  2840  1.65   12  0.62  1.17   
24    LiHg  0.98   1  0.99  1.93   3   5.39  146  1615  2.00   12  0.57  1.21   
25    MgHg  1.31   2  0.86  1.42  12   7.65  127  1363  2.00   12  0.57  1.21   
26    LiPb  0.98   1  0.99  1.93   3   5.39  146  1615  2.33    4  0.71  1.06   
27    LiTl  0.98   1  0.99  1.93   3   5.39  146  1615  1.62    3  0.67  1.13   
28    MgTl  1.31   2  0.86  1.42  12   7.65  127  1363  1.62    3  0.67  1.13   
29    LiAl  0.98   1  0.99  1.93   3   5.39  146  1615  1.61    3  0.75  1.09   
30    LiCd  0.98   1  0.99  1.93   3   5.39  146  1615  1.69   12  0.67  1.26   
31    LiGa  0.98   1  0.99  1.93   3   5.39  146  1615  1.81    3  0.65  1.01   
32    LiIn  0.98   1  0.99  1.93   3   5.39  146  1615  1.78    3  0.78  1.15   
33    NaIn  0.93   1  1.01  2.35  11   5.14   97  1156  1.78    3  0.78  1.15   
34    LiZn  0.98   1  0.99  1.93   3   5.39  146  1615  1.65   12  0.62  1.17   
35    NaTl  0.93   1  1.01  2.35  11   5.14   97  1156  1.62    3  0.67  1.13   
36    LiBi  0.98   1  0.99  1.93   3   5.39  146  1615  2.02    5  0.71  1.00   
37    NaBi  0.93   1  1.01  2.35  11   5.14   97  1156  2.02    5  0.71  1.00   
38    NaPb  0.93   1  1.01  2.35  11   5.14   97  1156  2.33    4  0.71  1.06   
39     KPb  0.82   1  1.34  2.68  19   4.34   80  1032  2.33    4  0.71  1.06   
40     KSn  0.82   1  1.34  2.68  19   4.34   80  1032  1.96    4  0.78  1.06   
41    BaCd  1.69  12  0.67  1.26  48   8.99  100  1038  0.89    2  1.52  2.29   
42    BaHg  0.89   2  1.52  2.29  56   5.21  142  2171  2.00   12  0.57  1.21   
43    HgSn  1.96   4  0.78  1.06  50   7.34  296  2543  2.00   12  0.57  1.21   

    x13    x14  x15   x16     y  
0    47   7.58  251  2436   938  
1    82   7.42  178  2013  1123  
2    56   5.21  142  2171  1418  
3    32   7.90  331  3103  1573  
4    20   6.11  154  1757  1518  
5    50   7.34  296  2543  1260  
6    38   5.70  144  1657  1423  
7    38   5.70  144  1657  1438  
8    81   6.11  164  1746   723  
9    48   8.99  1

In [3]:
X = df.drop(['formula','y'], axis = 1)
y = df['y'].values

In [4]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X,y)

LinearRegression()

In [5]:
print(lr.coef_)
print(lr.intercept_)

[ 1.76853420e+02  1.86880756e+01  8.28615180e+02 -1.94320662e+02
 -4.11919518e+00  4.98595805e+00  1.26575181e+00  9.41354704e-02
 -1.46803463e+02 -1.17557184e+01  2.40644034e+02 -9.76166090e+01
 -1.63683023e-01  1.08046305e+02  3.01526716e-01  1.67467901e-01]
-934.1054785436244


In [6]:
print(lr.score(X, y))

0.7596665868239196


In [7]:
from sklearn.metrics import mean_absolute_error as mae, mean_squared_error as mse

print('MAE = %.3f' % mae(y_true = y, y_pred = lr.predict(X)))
print('MSE = %.3f' % mse(y_true = y, y_pred = lr.predict(X)))

MAE = 90.924
MSE = 14575.416


In [8]:
X.shape

(44, 16)

In [9]:
#留出法
X_train, y_train = X[:-10], y[:-10] #切片，从头取到倒数第十一个
X_test, y_test = X[-10:], y[-10:] #从倒数第十个取到最后一个

In [10]:
X_train.shape, X_test.shape

((34, 16), (10, 16))

In [11]:
lr_lo = LinearRegression()
lr_lo.fit(X_train, y_train)

LinearRegression()

In [13]:
R2_lo = lr_lo.score(X_test, y_test)
print('R2 = ', R2_lo)
print('RMSE = %.3f' % np.sqrt(mse(y_true = y_test, y_pred = lr_lo.predict(X_test))))

R2 =  0.12868842172355188
RMSE = 170.176


In [ ]:
#多次留出法，使用shuffle

In [17]:
#交叉验证
from sklearn.model_selection import cross_val_score

rmse_scores = cross_val_score(lr, X, y, scoring = 'neg_root_mean_squared_error', cv = 10) #10折交叉验证

print('Folds: %i, mean RMSE:%.3f' % (len(rmse_scores), -np.mean(rmse_scores)))

Folds: 10, mean RMSE:194.253


In [18]:
rmse_scores

array([-173.4269534 , -227.93660288, -285.71293073, -303.63090744,
       -246.03126924, -121.67757828, -144.26123768, -132.82482933,
       -171.70462769, -135.32205122])

In [21]:
#留一法，交叉法中cv = len(X)，或者手打。效果好，但是训练量大
from sklearn.model_selection import LeaveOneOut

sample_x = [1, 2, 3, 4, 5]
loo = LeaveOneOut()
for train, test, in loo.split(sample_x):
    print(train, test)

[1 2 3 4] [0]
[0 2 3 4] [1]
[0 1 3 4] [2]
[0 1 2 4] [3]
[0 1 2 3] [4]


In [32]:
#自助法。取样测试放回，再取没有被抓到的样测试

from sklearn.utils import resample

X_train, y_train = resample(X, y)

index_test = set(X.index) - set(X_train.index)

In [38]:
X_train.shape, y_train.shape

((44, 16), (44,))

In [34]:
X_test = X.iloc[list(index_test)]
y_test = y[list(index_test)]

In [35]:
X_test.shape, y_test.shape

((14, 16), (14,))

In [36]:
lr_bs = LinearRegression()
lr_bs.fit(X_train, y_train)

LinearRegression()

In [37]:
print('MSE = %.3f'% np.sqrt(mse(y_true=y_test, y_pred=lr_bs.predict(X_test))))

MSE = 207.141
